version: "3.5"

services:
  db:
    container_name: postgres-cinemaDb
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "cinema_app_user"
      POSTGRES_PASSWORD: "cinema_app_pasw"
      POSTGRES_DB: "CinemaTicketBookingDB"
    ports:
      - "5432:5432"
    networks:
      - default

networks:
  default:
    name: cinema-api
    driver: bridge